### ISSUE TITLE
Some chord names not highlighted

### ISSUE THREAD

**Issue by RBekking** [gusper/SongTxt-vscode#18]
Certain common chord names aren't recognised:
Example: 

- Bm7b5
- Cmaj9#11
- Adim

etc...

**Comment by contributor** [comment]
up

**Comment by c-d** [comment]
Do you have any other example variations that are being missed? Or a reference to possible valid chord names? 

I don't have great knowledge of music theory but here's a tweaked regex for the above: https://regex101.com/r/fIqVVI/3

**Comment by RBekking** [comment]
Thank you @c-d 

I made a regex myself which kind of covers all the chords I've encountered so far:

**Comment by c-d** [comment]
Nice, thanks. Hope you don't mind me raising a PR with your changes (though I'm not sure if PR's are being accepted on this repo...)

**Comment by RBekking** [comment]
Oh wait I miss-read. Offcourse you can do whatever you want with the code
I've shared.

Richard Bekking


Bekking Electronics Design
tel: +31630397999
electronicsdesign.nl

**Comment by gusper** [comment]
I'll happily take a PR. :)

**Comment by RBekking** [comment]
You're welcome! I love your plugin, I use it a lot.

I'll see if I can raise you a PR after work.
Cheers,

Richard Bekking


Bekking Electronics Design
tel: +31630397999
electronicsdesign.nl

**Comment by gusper** [comment]
Finally got around to publishing the version with your updates a couple days ago. Thanks again, guys!
